services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - 8080:8080
      - 8081:8081

      
  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432

  client:
    build:
      context: .
      dockerfile: Client/Dockerfile
    ports:
      - 80:80
